[package]
name = "prost"
# NB: When modifying, also modify html_root_url in lib.rs
version = "0.5.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
repository = "https://github.com/danburkert/prost"
documentation = "https://docs.rs/prost"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."
keywords = ["protobuf", "serialization"]
categories = ["encoding"]
edition = "2018"

[badges]
travis-ci = { repository = "danburkert/prost" }
appveyor = { repository = "danburkert/prost" }

[workspace]
members = [
  "conformance",
  "prost-build",
  "prost-derive",
  "prost-types",
  "protobuf",
  "tests",
  "tests-2015",
  "tests-alloc",
]
exclude = [
  # The fuzz crate can't be compiled or tested without the 'cargo fuzz' command,
  # so exclude it from normal builds.
  "fuzz",
]

[features]
default = ["prost-derive", "std"]
no-recursion-limit = []
std = []
   # When std is disabled, we attempt to provide no_std support in prost
   # Config::use_alloc_collections() should be set when using prost_build in your build.rs
   # so that generated files will not have std:: either, and will use alloc crate instead

[dependencies]
bytes = { git = "https://github.com/tokio-rs/bytes", rev = "c17e40115f5bb2a2db71ed90dceae6ec643dc024" }
prost-derive = { version = "0.5.0", path = "prost-derive", optional = true }

[dev-dependencies]
criterion = "0.2"
env_logger = { version = "0.6", default-features = false }
failure = "0.1"
log = "0.4"
protobuf = { version = "0", path = "protobuf" }
quickcheck = "0.8"

[[bench]]
name = "varint"

[[bench]]
name = "benchmark"
harness = false
